name: Code quality

on: [push]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          dry: True
          prettier_version: '2.8.4'
          prettier_options: --check src
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: npm run lint
